//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movieproject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltheatre
    {
        public int theatreid { get; set; }
        public string theatre { get; set; }
        public Nullable<int> locid { get; set; }
    
        public virtual tbllocation tbllocation { get; set; }
    }
}
